# -*- coding: utf-8 -*-
"""json_output.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DKpDwat1rOIxCpXYPOyyaoFj8aBif0_
"""

import json
from ultralytics import YOLO

model = YOLO('yolov8n.pt')


results = model('/content/Traffic video  for object detection and tracking.mp4')


json_data = []


for result in results:
    boxes = result.boxes
    frame_data = {}
    detections = []


    for box in boxes:
        detection = {
            'coordinates': box.xyxy[0].tolist(),
            'confidence': float(box.conf[0]),
            'class': model.names[int(box.cls[0])]
        }

        detections.append(detection)

    frame_data["detections"] = detections
    json_data.append(frame_data)


json_string = json.dumps(json_data, indent=4)


print(json_string)
with open('detections.json', 'w') as f:
    f.write(json_string)

json_data = []


for result in results:
    boxes = result.boxes
    frame_data = {}
    detections = []


    for i, box in enumerate(boxes):
        detection = {
            "object": model.names[int(box.cls[0])],
            "id": i,
            "bbox": box.xyxy[0].tolist(),
        }

        if i % 2 == 0 and len(boxes) > i +1:
          detection["subobject"] = {
              "object": model.names[int(boxes[i+1].cls[0])],
              "id": i+1,
              "bbox": boxes[i+1].xyxy[0].tolist()
          }

        detections.append(detection)

    frame_data["detections"] = detections
    json_data.append(frame_data)


json_string = json.dumps(json_data, indent=4)

print(json_string)

with open('detections_with_subobjects.json', 'w') as f:
    f.write(json_string)